"""Keep caches generated by released datacache usable without rewriting them."""

from contextlib import closing
import gzip
import json
import os
from pathlib import Path
import sqlite3
import stat

import pandas as pd
import pytest

from datacache import (
    Cache, build_local_filename, connect_if_correct_version,
    db_from_dataframe, db_from_dataframes_with_absolute_path,
    fetch_and_transform, fetch_csv_db, fetch_file,
)
from datacache import database_helpers, database_table, download
from datacache import common


FIXTURES = Path(__file__).parent / "fixtures"
NAMES = json.loads((FIXTURES / "legacy_v191_names.json").read_text())


def legacy_database(path):
    with closing(sqlite3.connect(path)) as connection:
        connection.executescript((FIXTURES / "legacy_v191.sql").read_text())
    return path


def reject(*args, **kwargs):
    pytest.fail("a legacy cache hit attempted a write, download, or rebuild")


@pytest.mark.parametrize("api", ["dataframe", "absolute", "cache", "version", "csv"])
def test_legacy_database_reuse_is_read_only_and_keeps_schema(tmp_path, monkeypatch, api):
    path = legacy_database(tmp_path / "records.db")
    before = path.read_bytes()
    inode = path.stat().st_ino
    # Old builds ignored this unnormalized primary key. Reuse must not apply
    # new-build constraints or reconstruct a frame just to open the database.
    path.chmod(0o444)
    tmp_path.chmod(0o555)
    cache = Cache(cache_root=tmp_path)
    try:
        with monkeypatch.context() as guard:
            guard.setattr(database_helpers, "build_tables", reject)
            guard.setattr(database_helpers, "fetch_csv_dataframe", reject)
            guard.setattr(os, "makedirs", reject)
            guard.setattr(download, "_download_to_temp_file", reject)
            if api == "dataframe":
                connection = db_from_dataframe(path, "records", None, primary_key="sample id", version=7)
            elif api == "absolute":
                connection = db_from_dataframes_with_absolute_path(path, {"records": None}, version=7)
            elif api == "cache":
                connection = cache.db_from_dataframe("records.db", "records", None, version=7)
            elif api == "csv":
                connection = fetch_csv_db("records", "https://offline.invalid/source.csv",
                                          db_filename="records.db", version=7,
                                          download_options={"cache_root": tmp_path})
            else:
                connection = connect_if_correct_version(path, 7, read_only=True)
            with closing(connection):
                assert connection.execute("SELECT * FROM records").fetchall() == [(1, "case"), (2, "control")]
                # Keep the old schema exactly, including its missing PK.
                assert not any(row[-1] for row in connection.execute("PRAGMA table_info(records)"))
                assert connection.execute("SELECT version FROM _datacache_metadata").fetchone() == (7,)
        assert path.read_bytes() == before
        assert path.stat().st_ino == inode
        assert stat.S_IMODE(path.stat().st_mode) == 0o444
        assert list(tmp_path.iterdir()) == [path]
    finally:
        tmp_path.chmod(0o755)
        path.chmod(0o644)


def test_legacy_blob_values_are_not_guessed_or_migrated(tmp_path):
    path = legacy_database(tmp_path / "records.db")
    blob = b"\x01\x00\x00\x00\x00\x00\x00\x00"
    with closing(sqlite3.connect(path)) as connection:
        connection.execute("UPDATE records SET sample_id = ? WHERE label = 'case'", (blob,))
        connection.commit()
    before = path.read_bytes()
    with closing(db_from_dataframe(path, "records", None, version=7)) as connection:
        assert connection.execute("SELECT sample_id FROM records WHERE label = 'case'").fetchone() == (blob,)
    assert path.read_bytes() == before


def test_legacy_csv_database_filename_is_preserved(tmp_path, monkeypatch):
    name = NAMES["csv_database_filename"]
    path = tmp_path / name
    with closing(sqlite3.connect(path)) as connection:
        connection.executescript("CREATE TABLE records (id INT, label TEXT);"
                                 "INSERT INTO records VALUES (42, 'legacy');"
                                 "CREATE TABLE _datacache_metadata (version INT);"
                                 "INSERT INTO _datacache_metadata VALUES (1);")
    # Source has the same schema/count used to generate the old key. Contents
    # differ so rebuilding or looking under a new key is observable.
    (tmp_path / "records.csv").write_text("id,label\n1,case\n2,control\n")
    before = path.read_bytes()
    monkeypatch.setattr(download, "_download_to_temp_file", reject)
    with closing(fetch_csv_db("records", "https://offline.invalid/records.csv.gz",
                               csv_filename="records.csv.gz",
                               download_options={"cache_root": tmp_path})) as connection:
        assert connection.execute("SELECT * FROM records").fetchall() == [(42, "legacy")]
    assert path.read_bytes() == before
    assert list(tmp_path.glob("*.db")) == [path]


@pytest.mark.parametrize("case", NAMES["filenames"])
def test_released_download_keys_and_private_files_are_reused(tmp_path, monkeypatch, case):
    assert build_local_filename(case["url"], decompress=case["decompress"]) == case["filename"]
    path = tmp_path / case["filename"]
    path.write_bytes(b"old installed bytes")
    path.chmod(0o600)
    before = path.stat()
    monkeypatch.setattr(download, "_download_to_temp_file", reject)
    monkeypatch.setattr(os, "chmod", reject)
    assert fetch_file(case["url"], decompress=case["decompress"], cache_root=tmp_path) == str(path)
    assert path.read_bytes() == b"old installed bytes"
    assert path.stat().st_ino == before.st_ino
    assert stat.S_IMODE(path.stat().st_mode) == 0o600


def test_existing_custom_transform_works_without_source(tmp_path, monkeypatch):
    path = tmp_path / "output.txt"
    path.write_text("old transformation")
    path.chmod(0o600)
    monkeypatch.setattr(download, "fetch_file", reject)
    assert fetch_and_transform("output.txt", reject, lambda p: Path(p).read_text(),
                               "missing.txt", "https://offline.invalid/missing.txt",
                               cache_root=tmp_path) == "old transformation"
    assert stat.S_IMODE(path.stat().st_mode) == 0o600


def test_build_does_not_require_new_pandas_scalar_or_row_apis(tmp_path, monkeypatch):
    # Also run this module on pandas <1.5 in CI. Feature removal catches
    # accidental reintroduction of newer APIs in the ordinary numeric path.
    frame = pd.DataFrame({"id": [2**53 + 1], "weight": [1.5], "missing": [float("nan")]})
    monkeypatch.delattr(pd, "NA", raising=False)
    monkeypatch.delattr(pd, "isna", raising=False)
    monkeypatch.setattr(pd.DataFrame, "itertuples", reject)
    with closing(db_from_dataframe(tmp_path / "data.db", "records", frame)) as connection:
        assert connection.execute("SELECT * FROM records").fetchall() == [(2**53 + 1, 1.5, None)]


def test_new_database_is_readable_with_legacy_sql(tmp_path):
    path = tmp_path / "new.db"
    frame = pd.DataFrame({"sample id": [1, 2], "label": ["case", "control"]})
    with closing(db_from_dataframe(path, "records", frame, primary_key="sample id", version=7)):
        pass
    with closing(sqlite3.connect(path)) as old_reader:
        assert old_reader.execute("SELECT version FROM _datacache_metadata").fetchone() == (7,)
        assert old_reader.execute("SELECT sample_id, label FROM records").fetchall() == [(1, "case"), (2, "control")]


@pytest.mark.parametrize("new_source", [False, True])
def test_transform_reuses_misplaced_legacy_source_without_moving_it(tmp_path, monkeypatch, new_source):
    monkeypatch.setattr(common, "get_data_dir", lambda subdir=None: str(tmp_path / (subdir or "default")))
    default = tmp_path / "default"
    default.mkdir()
    legacy = default / "source.txt"
    legacy.write_text("old source")
    legacy.chmod(0o600)
    before = legacy.stat()
    if new_source:
        current = tmp_path / "project" / "source.txt"
        current.parent.mkdir()
        current.write_text("new source")
    monkeypatch.setattr(download, "_download_to_temp_file", reject)

    def transform(source_path, output_path):
        text = Path(source_path).read_text()
        Path(output_path).write_text(text.upper())
        return text.upper()

    result = fetch_and_transform("output.txt", transform, lambda p: Path(p).read_text(),
                                 "source.txt.gz", "https://offline.invalid/source.txt.gz", subdir="project")
    assert result == ("NEW SOURCE" if new_source else "OLD SOURCE")
    assert legacy.read_text() == "old source"
    assert legacy.stat().st_ino == before.st_ino
    assert stat.S_IMODE(legacy.stat().st_mode) == 0o600


def test_explicit_csv_database_still_honors_source_integrity(tmp_path):
    path = legacy_database(tmp_path / "records.db")
    source = tmp_path / "source.csv"
    source.write_text("sample id,label\n1,case\n2,control\n")
    before = path.read_bytes()
    with pytest.raises(download.FileValidationError, match="SHA-256"):
        fetch_csv_db("records", source.as_uri(), db_filename="records.db", version=7,
                     download_options={"cache_root": tmp_path, "expected_sha256": "0" * 64})
    assert path.read_bytes() == before
