-- Generated by datacache 1.9.1 at ee20b5a, before these changes.
BEGIN TRANSACTION;
CREATE TABLE "_datacache_metadata" ("version" INT);
INSERT INTO "_datacache_metadata" VALUES(7);
CREATE TABLE "records" ("sample_id" INT NOT NULL, "label" TEXT NOT NULL);
INSERT INTO "records" VALUES(1,'case');
INSERT INTO "records" VALUES(2,'control');
COMMIT;
